server:
  port: 8091

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
  health:
    case-document-am-api.enabled: ${SECURE_DOC_STORE_FEATURE:false}

spring:
  application:
    name: sscs evidence share
  main:
    allow-bean-definition-overriding: true

http:
  connect:
    timeout: 5000
    request:
      timeout: 5000
    read:
      timeout: 5000

send-grid:
  host: smtp.sendgrid.net
  port: 587
  api-key: dummy
ld:
  user-key: sscs-evidence-share
  sdk-key: abcd

service:
  pdf-service:
    uri: ${PDF_SERVICE_BASE_URL:https://docmosis.aat.platform.hmcts.net/rs/render}
    accessKey: ${PDF_SERVICE_ACCESS_KEY:}
    health:
      uri: ${PDF_SERVICE_HEALTH_URL:https://docmosis.aat.platform.hmcts.net/rs/status}

amqp:
  host: ${AMQP_HOST:localhost}
  username: ${AMQP_USERNAME:guest}
  password: ${AMQP_PASSWORD:}
  topic: ${TOPIC_NAME:test.topic}
  subscription: ${SUBSCRIPTION_NAME:test.queue}
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: ${TRUST_ALL_CERTS:true}

document:
  pdf:
    hmctsImgKey: hmcts2
    hmctsImgVal: "[userImage:hmcts.png]"
    hmctsWelshImgKey: welshhmcts2
    hmctsWelshImgVal: "[userImage:welshhmcts.png]"

document_management.url: ${DOCUMENT_MANAGEMENT_URL:http://dm-store:5005}

send-letter:
  url: ${SEND_LETTER_SERVICE_BASEURL:http://localhost:4021}
  enabled: ${SEND_LETTER_SERVICE_ENABLED:true}
  maxRetryAttempts: ${MAX_RETRY_ATTEMPTS:3}

idam:
  url: ${IDAM_API_URL:http://localhost:5000}
  s2s-auth:
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
    url: ${IDAM_S2S_AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}
    jwkUrl: ${IDAM_API_JWK_URL:http://localhost:5000/jwks}
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
    secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirect_url: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}

appeal:
  email:
    host: ${EMAIL_SERVER_HOST:localhost}
    port: ${EMAIL_SERVER_PORT:1025}
    smtp:
      tls.enabled: ${EMAIL_SMTP_TLS_ENABLED:true}
      ssl.trust: ${EMAIL_SMTP_SSL_TRUST:*}

robotics:
  email:
    from: ${ROBOTICS_EMAIL_FROM:sscs@hmcts.net}
    from-send-grid: noreply@mail-sscs-nonprod.platform.hmcts.net
    to: ${ROBOTICS_EMAIL_TO:receiver@hmcts.net}
    scottishTo: ${ROBOTICS_EMAIL_SCOTTISH_TO:receiver2@hmcts.net}
    pipAeTo: ${ROBOTICS_EMAIL_PIP_AE_TO:receiver3@hmcts.net}
    message: ${ROBOTICS_EMAIL_MESSAGE:Please find attached the robotics json file \nPlease do not respond to this email}
  schema.resource.location: /schema/sscs-robotics.json
  englishCount: 3
  scottishCount: 1

wlu:
  email:
    from: ${WLU_EMAIL_FROM:noreply@mail-sscs-nonprod.platform.hmcts.net}
    from-send-grid: noreply@mail-sscs-nonprod.platform.hmcts.net
    to: ${WLU_EMAIL_TO:sscs-tests@HMCTS.NET}
    subject: ${WLU_EMAIL_SUBJECT:Welsh translation â€“}
    message: ${WLU_EMAIL_MESSAGE:Please find attached the files along with request translation form.\nThank you
      very much}
    dateOfReturn: ${WLU_RETURN_DATE:24 hours from requested date.}

docmosis:
  template:
    english:
      dl6:
        name: TB-SCS-GNO-ENG-00010.doc
      dl16:
        name: TB-SCS-GNO-ENG-00011.doc
      d609-97:
        name: TB-SCS-GNO-ENG-00068.doc
      d609-98:
        name: TB-SCS-GNO-ENG-00069.doc
    welsh:
      dl6:
        name: TB-SCS-GNO-ENG-00010.doc
      dl16:
        name: TB-SCS-GNO-ENG-00011.doc
      d609-97:
        name: TB-SCS-GNO-WEL-00469.docx
      d609-98:
        name: TB-SCS-GNO-WEL-00470.docx

evidence-share:
  submit-types:
  - PAPER

exela:
  addressLine1: HMCTS SSCS
  addressLine2: PO BOX 12626
  addressLine3: Harlow
  addressPostcode: CM20 9QF
  scottishAddressLine2: PO BOX 13150
  scottishPostcode: CM20 9TT

feature:
  urgent-hearing.enabled: ${URGENT_HEARING_ENABLED:false}
  scottish-po-box.enabled: ${SCOTTISH_PO_BOX_ENABLED:false}
  secure-doc-store.enabled: ${SECURE_DOC_STORE_FEATURE:false}
  enhancedConfidentiality.enabled: ${ENHANCED_CONFIDENTIALITY_FEATURE:false}

case_document_am.url: ${CASE_DOCUMENT_AM_URL:http://localhost:4455}

pdf:
  api:
    url: ${PDF_API_URL:http://localhost:5500}

dwp:
  response:
    due:
      days: ${DWP_RESPONSE_DUE_DAYS:35}
      days-child-support: ${DWP_RESPONSE_DUE_DAYS_CHILD_SUPPORT:42}
